name: CRUD App CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  # Build và Deploy lên server
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/crud-app:latest

      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Di chuyển vào thư mục dự án trên server (tạo nếu chưa có)
            cd ~/crud-app || exit 1

            # Ghi file docker-compose cho production từ secret
            echo "${{ secrets.DOCKER_COMPOSE_PROD_FILE }}" > docker-compose.prod.yml

            # Kiểm tra xem file docker-compose có hợp lệ không
            docker-compose -f docker-compose.prod.yml config > /dev/null || {
              echo "Lỗi: File docker-compose.prod.yml không hợp lệ."
              cat docker-compose.prod.yml
              exit 1
            }

            # Đăng nhập vào Docker Hub trên server
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # Pull image mới nhất
            docker pull ${{ secrets.DOCKER_USERNAME }}/crud-app:latest

            # Dừng và xóa container cũ
            docker ps -a --filter "name=crud-app-backend" --format '{{.ID}}' | xargs -r docker stop || true
            docker ps -a --filter "name=crud-app-backend" --format '{{.ID}}' | xargs -r docker rm || true

            # Khởi động container mới bằng file compose của production
            docker-compose -f docker-compose.prod.yml up -d

            # Dọn dẹp các image cũ không còn được sử dụng
            docker image prune -f